app/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # (?P<article_id>\d+)为一个组, 其中?P<article_di>中的article_id代表了该组的组名
    url(r'^article/(?P<article_id>\d+)$', cache_page(60 * 15)(views.ArticleDetailView.as_view()), name='detail'),
    url(r"^category/(?P<cate_id>\d+)$", views.CategoryView.as_view(), name='category'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentView, name='comment'),
    url(r'^search/$', views.blog_search, name='search'),
    url(r'^about_me/$', views.suggest_view, name='about_me'),
    url(r'^tags/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^thanks/$', views.thanks, name='thanks')
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]

app/templates/blog/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'app:about_me' %}">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" style="padding: 20px;"><h1 id="h1-about-me"><a name="About me" class="reference-link"></a><span class="header-link octicon octicon-link"></span>About me</h1><hr>
        <p><strong>My name is Jiang WenMing(姜闻名),I was born in 1994s.</strong></p>
        <br>
        <p><strong>I used to major in Civil Engineering. But now, i am a fresh man on CS.</strong></p>
        <p><strong> During the past times, i am just coding and coding, learning and learning. In order to become a Web developer,</strong></p>
        <p><strong>  I’ll keep on coding and learning. By th way, i am familiar with Python, Mysql, CSS, HTML.etc. </strong></p>
        <br>
        <p><strong>In the sapce time, i will read some books, surfing the internet and do some exercise.</strong></p>
        <hr>
        <h1 id="h1-contact-me"><a name="Contact me" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Contact me</h1><hr>
        <ul>
            <li><strong><a href="https://github.com/tomming233" title="Github">Github</a></strong></li>
            <li><strong>Email: <a href="mailto:tomming233@gmail.com">tomming233@gmail.com</a></strong></li>
        </ul>
        <hr>
        <h1 id="h1-suggest-me"><span class="header-link octicon octicon-link"></span>Suggest to me</h1><hr>
        <form class="form-inline" method="POST">
            {% csrf_token %}
            {% for field in form %}
            {{ field }}
            {% endfor %}
            <br><br>
            <input type="submit" value="Submit" />
        </form>
    </div>


    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p style="text-align: center;">Copyright &copy; 姜闻名的博客 2016</p>
            </div>
            <!-- /.col-lg-12 -->
            <div class="col-lg-12" style="text-align: center;">
                <a href="https://github.com/tomming233/blog">Github</a>
            </div>

        </div>
        <!-- /.row -->
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'app:about_me' %}">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p style="text-align: center;">Copyright &copy; 姜闻名的博客 2016</p>
            </div>
            <!-- /.col-lg-12 -->
            <div class="col-lg-12" style="text-align: center;">
                <a href="https://github.com/tomming233/blog">Github</a>
            </div>

        </div>
        <!-- /.row -->
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/blog/category.html
<!--category-->
<div class="well">
    <h4><span class="glyphicon glyphicon-align-justify"></span>    博客目录</h4>
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled">
            {% for category in category_list %}
                <li class="cat-item"><span class="glyphicon glyphicon-chevron-right"></span><a
                        href="{% url 'app:category' category.pk %}">    {{ category.name }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!--标签云-->
<div class="well">
    <h4><span class="glyphicon glyphicon-align-justify"></span>    标签云</h4>
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled">
            {% for tag in tag_list %}
                <li class="cat-item"><span class="glyphicon glyphicon-tag"></span><a
                        href="{% url 'app:tag' tag.pk %}">    {{ tag.name }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>

app/templates/blog/comment.html
<div class="col-sm-12" style ='background-color: #ccffcc;'>
    <h4 class="'lead">评论详情</h4>
    <form method="post" action="{% url 'app:comment' article.pk %}">
        {% csrf_token %}
        {% for field in form %}
        {{ field }}
        {{ field.errors }}
        <br>
        {% endfor %}
        <button type="submit">评论</button>
    </form>
    <hr>
    {% for comment in comment_list %}
        <span class="'user-nickname">{{ comment.user_name }}</span>
        <time class="time">{{ comment.created_time }}</time>
        <div class="comment-content">{{ comment.body }}</div>
        <div><a href="">回复</a></div>
    <hr>
    {% endfor %}
</div>

app/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-8" style ='background-color: #f2f2f2;'>
            <div class="text-center">
                <h2><a href="{% url 'app:detail' article.pk %}">{{ article.title }}</a></h2>
                <p><span class="glyphicon glyphicon-time"></span> {{ article.created_time }}</p>
                <br>
            </div>
            <span class="post-views">阅读量: {{ article.views }}</span>
            <div>
            <p class="lead">{{ article.body | safe}}</p>
            </div>

            <hr><br><br>

            {% include 'blog/comment.html' %}

        </div>

       <!-- 博客旁列 -->
        <div class="col-md-4">

            <!-- Blog Search Well -->

            <div class="well">
                <h4>Blog Search</h4>
                <form action="/search/" method="get">
                    <div class="input-group">
                        <input type="text" name="search_for" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <!--tag well-->
            {% include "blog/category.html" %}



            <!-- Side Widget Well -->
            <div class="well">
                <h4><span class="glyphicon glyphicon-align-justify"></span>    博客介绍</h4>
                <p>欢迎来到我的个人博客，此博客主要用于记录技术随笔，个人感想等各种杂文。由于初学编程，个中纰漏，望请指出，谢谢！</p>
            </div>

        </div>
    </div>

</div>

{% endblock content %}

app/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">

    <div class="row">

        <!-- 博客页面实体 -->
        <div class="col-md-8">
            <!-- 博客正文实体 -->
            <h1 class="page-header">
                {% if cate_name %}
                    分类：{{ cate_name }}
                {% elif tag_name %}
                    标签: {{ tag_name }}
                {% else %}
                    我的文章
                {% endif %}
            </h1>

            <!-- 博客正文 -->
            <div>
                {% load paginate_tags %}
                {% paginate article_list 3 %}
                {% for article in article_list %}
                <div>
                    <h2>
                        <a href="{% url 'app:detail' article.pk %}">{{ article.title }}</a>
                    </h2>
                    <p><span class="glyphicon glyphicon-time"></span> {{ article.created_time }}</p>
                    <hr>
                    <p>{{ article.body | safe | truncatewords:10}}</p>
                </div>
                <div><a class="btn btn-primary" href="{% url 'app:detail' article.pk %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a></div>
                <span class="post-views">阅读量: {{ article.views }}</span>
                <hr>
                {% endfor %}
            </div>
            <div>
                {% include 'blog/pagination.html' %}
            </div>

        </div>

        <!-- 博客旁列 -->
        <div class="col-md-4">

            <!-- Blog Search Well -->

            <div class="well">
                <h4>Blog Search</h4>
                <form action="/search/" method="get">
                    <div class="input-group">
                        <input type="text" name="search_for" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            {% include "blog/category.html" %}


            <!-- Side Widget Well -->
            <div class="well">
                <h4><span class="glyphicon glyphicon-align-justify"></span>    博客介绍</h4>
                <p>欢迎来到我的个人博客，此博客主要用于记录技术随笔，个人感想等各种杂文。由于初学编程，个中纰漏，望请指出，谢谢！</p>
            </div>

        </div>

    </div>
    <!-- /.row -->

</div>

{% endblock content %}

app/templates/blog/pagination.html
<ul class='pagination pagination-lg'>
    {% if article_list.has_previous %}
        <li><a href="?page={{ article_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li><a class="'disabled">&laquo;</a></li>
    {% endif %}


    {% for page in pages %}
        <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endfor %}

    {% if article_list.has_next %}
        <li><a href="?page={{ article_list.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li><a class="'disabled">&raquo;</a></li>
    {% endif %}
</ul>

app/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">

    <div class="row">

        <!-- 博客页面实体 -->
        <div class="col-md-8">
            <!-- 博客正文实体 -->
            <h1 class="page-header">
                {% if cate_name %}
                    分类：{{ cate_name }}
                {% elif tag_name %}
                    标签: {{ tag_name }}
                {% else %}
                    我的文章
                {% endif %}
            </h1>

            <!-- 博客正文 -->
            {% if article_list %}
                <div>
                    {% for article in article_list %}
                        <h2>
                            <a href="{% url 'app:detail' article.pk %}">{{ article.title }}</a>
                        </h2>
                        <p class="lead">
                            by Tom Ming</a>
                        </p>
                        <p><span class="glyphicon glyphicon-time"></span> {{ article.created_time }}</p>
                        <hr>
                    {% endfor %}
                </div>
            {% else %}
                <h3>抱歉，无搜索内容</h3>
            {% endif %}

        </div>

       <!-- 博客旁列 -->
        <div class="col-md-4">

            <!-- Blog Search Well -->

            <div class="well">
                <h4>Blog Search</h4>
                <form action="/search/" method="get">
                    <div class="input-group">
                        <input type="text" name="search_for" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <!--tag well-->
            {% include "blog/category.html" %}


            <!-- Side Widget Well -->
            <div class="well">
                <h4><span class="glyphicon glyphicon-align-justify"></span>    博客介绍</h4>
                <p>欢迎来到我的个人博客，此博客主要用于记录技术随笔，个人感想等各种杂文。由于初学编程，个中纰漏，望请指出，谢谢！</p>
            </div>

        </div>

    </div>
    <!-- /.row -->

</div>

{% endblock content %}

app/templates/blog/thanks.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'app:about_me' %}">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" style="padding: 20px;">
        <h1>意见已经收到, 非常感谢</h1>
    </div>


    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p style="text-align: center;">Copyright &copy; 姜闻名的博客 2016</p>
            </div>
            <!-- /.col-lg-12 -->
            <div class="col-lg-12" style="text-align: center;">
                <a href="https://github.com/tomming233/blog">Github</a>
            </div>

        </div>
        <!-- /.row -->
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>